#!/bin/bash

PPTP_USER=$([ -n "$1" ] && echo "$1" || echo "alttest")
PPTP_PWD=$([ -n "$2" ] && echo "$2" || echo "12qwaszx")

sudo apt-get update
sudo apt-get install -y pptpd
# listen to tcp 1723
# ppp 
sudo echo "localip 10.0.0.1" >> /etc/pptpd.conf
sudo echo "remoteip 10.0.0.101-200" >> /etc/pptpd.conf
sudo echo "$PPTP_USER pptpd $PPTP_PWD *" >> /etc/ppp/chap-secrets
sudo echo "ms-dns 8.8.8.8" >> /etc/ppp/pptpd-options
sudo echo "ms-dns 8.8.4.4" >> /etc/ppp/pptpd-options

sudo systemctl enable pptpd
sudo systemctl restart pptpd

# network
sudo echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
sudo sysctl -p

sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y iptables-persistent
sudo service netfilter-persistent save