#!/bin/bash
# 启动约需1分钟
echo && echo "install user_data_pptp"
# 将alttest改成自己的用户名，将12345678改成自己的密码
PPTP_USER=alttest
PPTP_PWD=12345678

sudo apt-get update >/dev/null 2>&1
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y pptpd iptables-persistent >/dev/null

# port: tcp/1723
# ppp
sudo echo "localip 10.10.10.1" >> /etc/pptpd.conf
sudo echo "remoteip 10.10.10.101-200" >> /etc/pptpd.conf
sudo echo "$PPTP_USER pptpd $PPTP_PWD *" >> /etc/ppp/chap-secrets
sudo echo "ms-dns 8.8.8.8" >> /etc/ppp/pptpd-options
sudo echo "ms-dns 8.8.4.4" >> /etc/ppp/pptpd-options

sudo systemctl enable pptpd
sudo systemctl restart pptpd

# network
sudo echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
sudo sysctl -qp

sudo iptables -t nat -A POSTROUTING -s 10.10.10.0/24 -o eth0 -j MASQUERADE
sudo service netfilter-persistent save
