#!/bin/bash

echo "start to install user_date_pptp"

# parameter
PPTP_USER=$([ -n "$1" ] && echo "$1" || echo "alttest")
PPTP_PWD=$([ -n "$2" ] && echo "$2" || echo "12qwaszx")

sudo apt-get update >/dev/null 2>&1
sudo apt-get install -y pptpd >/dev/null
# listen to tcp 1723
# ppp
sudo echo "localip 10.10.10.1" >> /etc/pptpd.conf
sudo echo "remoteip 10.10.10.101-200" >> /etc/pptpd.conf
sudo echo "$PPTP_USER pptpd $PPTP_PWD *" >> /etc/ppp/chap-secrets
sudo echo "ms-dns 8.8.8.8" >> /etc/ppp/pptpd-options
sudo echo "ms-dns 8.8.4.4" >> /etc/ppp/pptpd-options

sudo systemctl enable pptpd
sudo systemctl restart pptpd

# network
sudo echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
sudo sysctl -p

sudo iptables -t nat -A POSTROUTING -s 10.10.10.0/24 -o eth0 -j MASQUERADE
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y iptables-persistent
sudo service netfilter-persistent save

echo "finish to install user_date_pptp"
