#!/bin/bash

# parameter
PORT=$([ -n "$1" ] && echo $1 || echo 8388)
PWD=$([ -n "$2" ] && echo "$2" || echo "12qwaszx")
AEAD=$([ -n "$3" ] && echo "$3" || echo "chacha20-ietf-poly1305")

sudo apt-get update
sudo apt-get install -y shadowsocks-libev
# configuration
cat << EOF > $PORT.tmp
{
    "server":["::0", "0.0.0.0"],
    "mode":"tcp_and_udp",
    "server_port":$PORT,
    "password":"$PWD",
    "timeout":300,
    "method":"$AEAD",
    "fast_open":false
}
EOF
sudo mv -f ./$PORT.tmp /etc/shadowsocks-libev/config.json
# restart service
sudo systemctl enable shadowsocks-libev
sudo systemctl restart shadowsocks-libev
