#!/bin/bash
# 启动约需1分钟
echo && echo "install user_data_shadow"
# 将12qwaszx改成自己的密码
PWD=12qwaszx

sudo apt-get update >/dev/null 2>&1
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y shadowsocks-libev >/dev/null

# port: tcp/udp/8388
# passcode: $PWD
# AEAD: aes-256-cfb
cat << EOF > 8388.tmp
{
    "server":["::0", "0.0.0.0"],
    "mode":"tcp_and_udp",
    "server_port":8388,
    "password":"$PWD",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open":false
}
EOF
sudo mv 8388.tmp /etc/shadowsocks-libev/config.json
sudo systemctl enable shadowsocks-libev
sudo systemctl restart shadowsocks-libev

# port: tcp/udp/8389
# passcode: $PWD
# AEAD: chacha20-ietf-poly1305
PORT=8389
cat << EOF > 8389.tmp
{
    "server":["::0", "0.0.0.0"],
    "mode":"tcp_and_udp",
    "server_port":$PORT,
    "password":"$PWD",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "fast_open":false
}
EOF
sudo mv 8389.tmp /etc/shadowsocks-libev/$PORT.json
sudo systemctl enable shadowsocks-libev-server@$PORT.service
sudo systemctl restart shadowsocks-libev-server@$PORT.service

echo "end" && echo